### ISSUE TITLE
Richness and diversity as response variables

### ISSUE THREAD

**Issue by CecSve** [CecSve/InsectMobile_Diversity_and_Biomass#17]
Used for the carnet + metabarcoding manuscript - check and reuse code for this calculation.

**Comment by CecSve** [comment]
Fyi @bowlerbear  - based on this [paper](https://www.frontiersin.org/articles/10.3389/fmicb.2019.02407/full), I will generate a variable for estimated richness using the [breakaway package](https://cran.r-project.org/web/packages/breakaway/index.html). I have generated rarefied richness and rarefied Shannon diversity for the samples.

**Comment by bowlerbear** [comment]
brilliant. That looks like a perfect paper for us to follow.
So we are almost ready for analysis. Woohoo!!! Just shout when you want a meeting,

**Comment by CecSve** [comment]
I have updated the richness output so richness is calculated on the asvs with reads in samples and their BINs. Only filtering on unique BINs removed reads from the samples, which was not what we really wanted, so I filtered on the combination of sample ID and BIN for reads > 0. Will send the output now.
