### ISSUE TITLE
environmental data

### ISSUE THREAD

**Issue by bowlerbear** [CecSve/InsectMobile_Diversity_and_Biomass#19]
i have used the script from the biomass paper to process the environmental data for 2018
it is just saved in the main directory:
write.table(outputCast,file="environData_2018_DK.txt",sep="\t")

last time, we had a cleaned-data folder and put it in there, shall we do that again?

I will work on the 2019 data now but having some weird issues reading it in. Will keep trying.

**Comment by bowlerbear** [comment]
also, having some trouble reading in the 2019 data files, there seems to be a crop name column which wasn't in the equivalent 2018 files. And more column headings than data columns. Maybe we just just drop the crop name heading. It seems to work then.
but you should check since all in Danish

df <- read_delim("data/environmental_data/covariate-data/ruter2019buf1000_areas.txt",
                 "\t", escape_double = FALSE, trim_ws = TRUE)

**Comment by CecSve** [comment]
> last time, we had a cleaned-data folder and put it in there, shall we do that again?

No, let's just stick to the folders we have - there is so many already. As long as the change is in the script it should be clear what data is processed and what is not - we can update the readme file explaining which files are the cleaned versions used for the analysis

**Comment by bowlerbear** [comment]
sure, but still tell me which folder to save the cleaned data files in...

**Comment by CecSve** [comment]
> sure, but still tell me which folder to save the cleaned data files in...

Sorry! This is the structure:
![image](https://user-images.githubusercontent.com/54532645/177971648-1770ede2-8e98-4b2f-a886-b1b1d1140547.png)

I suppose the merged data can just be in the data folder? Or we can make a cleaned-data folder if you prefer

**Comment by bowlerbear** [comment]
yeah, lets make a cleaned_data folder along these. And I will put it in
there.

**Comment by CecSve** [comment]
> Maybe we just just drop the crop name heading. It seems to work then.
> but you should check since all in Danish

I have checked now - don't know what the crop name column header is doing in there and we can just remove it! Then the column headers and content should match between years.

**Comment by CecSve** [comment]
Files have been updated

**Comment by bowlerbear** [comment]
I think I have got as far as I can with script 04. But if the input data is ok, it should not produce a merged environmental data file for 2018 and 2019.
But you need to check it all makes sense.

Things I am not sure of
- what happened to the "oeko" land use. Seems to be different in the 2018 and 2019 files but maybe doesnt matter since I dont think that will make use of this
- which traffic light data to use for 2019
-whether the land use can be different between 2018 and 2019 for the route with the same ID. If a route slightly changed from one year to the next, was it given a new id?

I will leave these for you to solve.

**Comment by CecSve** [comment]
> * -whether the land use can be different between 2018 and 2019 for the route with the same ID. If a route slightly changed from one year to the next, was it given a new id?

No, it was not given a new ID. I have not gone through script 04, will today, and see how you merged the data - I would think the land cover columns should be year specific, since especially the farmland cover may vary between years.

**Comment by CecSve** [comment]
> * what happened to the "oeko" land use. Seems to be different in the 2018 and 2019 files but maybe doesnt matter since I dont think that will make use of this

Not sure what you mean by changed? The column header name is slightly different and the routeIDs are different, but the 2019 IDs can be translated to the correct IDs (one to one match). JB used different IDs for generating land cover data between the years but I have corrected it in earlier scripts.

**Comment by CecSve** [comment]
> * which traffic light data to use for 2019

For the new routes in 2019 we can use 'ruter2019_countStops', for the repeated routes and the routes in 2018, we should use 'DK_TrafficLightsCount', if that's what you are asking for?

**Comment by CecSve** [comment]
I see in 04 we make a separate category for heatland (not included in open uncultivated land). Do you remember how you did in Germany? I checked the biomass scripts for Germany and I am not sure whether the 'grassland' cover also includes heathland?

**Comment by bowlerbear** [comment]
lets just do the optimal analysis for Denmark and not worry about Germany

in Germany, grassland is just this vague 'green land' thing. I have no idea where heathland is. But dont worry about it. We dont have it as a category in the data processed by Volker.

**Comment by CecSve** [comment]
> > * -whether the land use can be different between 2018 and 2019 for the route with the same ID. If a route slightly changed from one year to the next, was it given a new id?
> 
> No, it was not given a new ID. I have not gone through script 04, will today, and see how you merged the data - I would think the land cover columns should be year specific, since especially the farmland cover may vary between years.

I have gone through 04 environ data handling now. The route ID can be identical between years since some volunteers (2/3 I would think) sampled the same route both years. The sample ID (for example P194.1) is unique and corresponds to a route. We now merge on route ID, but this occasionally give two unique rows since the land cover can be slightly different between years since we e.g. calculated farmland based on the crop type which we have yearly new data on.

I suppose when we merge environ data with sampling data, we can merge based on sampling year, sample ID and route ID to the environ route ID? Maybe we should have a chat if you have time?

**Comment by bowlerbear** [comment]
in the 2018 data, the oeko was included in the buffer files - look at your
2018 script and you will see that you didn't read in the separate oeko file
for 2018 - the line was commented out)
For 2019, I am not sure whether the same happened or whether we need to
read in this oeko file for 2019 this time

**Comment by CecSve** [comment]
We will not use the oeko data this time around (since we do not look at land use) - so I think it does not matter?
