### ISSUE TITLE
Land heterogeneity

### ISSUE THREAD

**Issue by bowlerbear** [CecSve/InsectMobile_Diversity_and_Biomass#4]
Lmer regression - land cover and heterogeneity prediction - test for biomass, richness and evenness

Need to think a bit more about what is our measure of heterogeneity.
As its simplest, it could be simply the Shannon diversity of the land cover proportions (but whether that is just based on the 5 dominant classes, or we use a finer habitat categorisation, is still to be decided)

**Comment by CecSve** [comment]
Do you have a good overview of which measures of heterogeneity are commonly used?

**Comment by bowlerbear** [comment]
Not really, I think people more commonly test habitat habitat (e.g., structural) heterogenity rather than land cover hetergeneity. But I think its ok if we test the latter. I have seen Shannon's diversity a few times for this. Will investigate!

**Comment by CecSve** [comment]
local patchiness may be relevant if a bird paper is ever possible

**Comment by bowlerbear** [comment]
we can use one of these
https://r-spatialecology.github.io/landscapemetrics/articles/new_metrics.html

**Comment by bowlerbear** [comment]
I have calculated the first simple measure of heterogeneity - see bottom of script 04

**Comment by bowlerbear** [comment]
just spotted this
might be worth a read
https://onlinelibrary.wiley.com/doi/10.1111/ele.14084?af=R

**Comment by CecSve** [comment]
Thanks - will take a look at it.

**Comment by CecSve** [comment]
Which buffer size has the largest effect and should be used to calculate heterogeneity?

- [ ] make effect plot for richness

**Comment by bowlerbear** [comment]
now all done
