### ISSUE TITLE
Analysis of 2 years?

### ISSUE THREAD

**Issue by bowlerbear** [CecSve/InsectMobile_Diversity_and_Biomass#7]
Previous analysis was just of 2018, but now we have 2 years. I propose we analyse both together:

- We can do this by:
- same model as before except with year as an additional fixed effect. We should not complicate it by any year x land cover interaction (i.e., we dont want to test whether land cover effects differ between the years). Instead, we should just focus on mean effects of the land cover across the years.
- We still need the transect as a random effect. It doesn't matter if some were only sampled in one year.

**Comment by CecSve** [comment]
I think most transects were sampled both years, but not all. Let's include how many in the manuscript!

I thought year would be a random effect? Although I do see the point of adding it as a fixed effect since we would expect much variation between those two years.

**Comment by bowlerbear** [comment]
if we had lots of years, year would be random. But we cant have year as a random effect with only 2 years (since random effects means we estimate a variance and we cant estimate much of a variance with 2 data points). It should be ok as a fixd effect.
