### ISSUE TITLE
Sub land use type

### ISSUE THREAD

**Issue by CecSve** [CecSve/InsectMobile_Diversity_and_Biomass#8]
We have a column with land use and one with sub land use type which originally was derived from the route. I have previously made a clunky attempt of standardizing the different variations (from Danish): https://github.com/CecSve/InsectMobile_Diversity_and_Biomass/blob/main/reports/02_Sampling_data.R - could we use this in any way for heterogeneity (count amount of land use + sub land use for each route)? I think it would probably make more sense to take this from the environmental variables we have with proportions. But just throwing the idea out there - otherwise I think we should disregard the rough land use categories all together and don't spend time standardizing them.

**Comment by bowlerbear** [comment]
ok, we can.
In the folder called Final_buffers_2018 there is a folder called p61 with a few more data rows in - were these just additional routes and I should add these data? or do we not use them for some reason?

**Comment by CecSve** [comment]
Let's check if the route ids are different.. i suspect that it may be one of those where it changed. Or that the pilots samples is missing from the main document. I'll check.

**Comment by CecSve** [comment]
@bowlerbear I've noticed some interesting crop codes for the farmland category that we probably should talk to Jesper about, e.g.:
- recreative purposes (part of the extensive layer) = 271
- afforestation types (part of the extensive layer) = 580, 581, 586, 587, 585, 589, 590, 591, 592, 593, 602, 603, 903, 311, 577, 578, 605

**Comment by CecSve** [comment]
> could we use this in any way for heterogeneity (count amount of land use + sub land use for each route)? 
I removed the standardisation raw land use categories because it got way to complex. Let's extract the info from the layers instead.

**Comment by bowlerbear** [comment]
yeah, we can use just the % cover of each route with each route as one measure of heterogeneity
But if you remember, we talked about another measure that accounted for the spatial configuration - a measure of local scale heterogeneity. For that, we really to use spatial layers.
